### ISSUE TITLE
DB Access

### ISSUE THREAD

**Issue by astradev** [edhor1608/DartConsole#1]
Bin gerade durch Zufall hier drauf gestoßen, als ich das Acitvity Board durchstöbert habe.

Ihr habt in Eurer DBAccess.cs noch das Passwort, sowie Benutzername und Server im Klartext drin stehen. Konnte mithilfe von phpMyAdmin (was auf dem Server liegt ...!!!) mich auf Eure Datenbank connecten. (http://jonas-rohde.de/phpmyadmin). Entweder Ihr klemmt noch eine .htaccess davor oder Pusht das Passwort nicht in das Public Repository...

Ist natürlich nur ein Tipp. Wollte so freundlich sein und Euch darauf hinweisen. :+1: 

P.S.: Habe nichts verändert, gelöscht oder ähnliches.

**Comment by edhor1608** [comment]
Servus, dank dir... mir war das schon bekannt und wollte mich bald darum kümmern, nur hab ich noch nicht den idealen Weg gefunden... werd mich dann aber zeitnah darum kümmern
